#include <stdio.h>
#include <string.h>

#define MAX 20
#define INF 9999

int n;

char router[MAX][20];

int cost[MAX][MAX];

int finalDist[MAX][MAX];

int finalNextHop[MAX][MAX];


/* Find router index */
int findRouter(char name[])
{
    int i;

    for (i = 0; i < n; i++)
    {
        if (strcmp(router[i], name) == 0)
        {
            return i;
        }
    }

    return -1;
}


/* Display separate LSP for every node */
void displayLSP()
{
    int i, j;
    int hasNeighbor;

    printf("\n\n================================================");
    printf("\n          LINK-STATE PACKETS (LSP)");
    printf("\n================================================");

    for (i = 0; i < n; i++)
    {
        printf("\n\nLSP generated by Router %s", router[i]);
        printf("\n----------------------------------------");

        hasNeighbor = 0;

        printf("\nNeighbor\tCost");

        for (j = 0; j < n; j++)
        {
            if (cost[i][j] != INF && i != j)
            {
                printf("\n%-15s%d",
                       router[j],
                       cost[i][j]);

                hasNeighbor = 1;
            }
        }

        if (hasNeighbor == 0)
        {
            printf("\nNo directly connected neighbors");
        }
    }

    printf("\n");
}


/* Display Initial Link-State Database */
void displayInitialMatrix()
{
    int i, j;

    printf("\n\n================================================");
    printf("\n       INITIAL LINK-STATE DATABASE");
    printf("\n================================================");

    printf("\n\n\t");

    for (j = 0; j < n; j++)
    {
        printf("%-8s", router[j]);
    }

    printf("\n");

    for (i = 0; i < n; i++)
    {
        printf("%-8s", router[i]);

        for (j = 0; j < n; j++)
        {
            if (cost[i][j] == INF)
            {
                printf("%-8s", "INF");
            }
            else
            {
                printf("%-8d", cost[i][j]);
            }
        }

        printf("\n");
    }
}


/*
   Dijkstra algorithm for one source
*/
void dijkstra(int source)
{
    int dist[MAX];
    int visited[MAX];
    int nextHop[MAX];

    int i, j;
    int min;
    int u;

    /* Initialization */

    for (i = 0; i < n; i++)
    {
        dist[i] = cost[source][i];

        visited[i] = 0;

        if (i == source)
        {
            nextHop[i] = -1;
        }
        else if (cost[source][i] != INF)
        {
            nextHop[i] = i;
        }
        else
        {
            nextHop[i] = -1;
        }
    }

    dist[source] = 0;


    /* Dijkstra */

    for (i = 0; i < n; i++)
    {
        min = INF;
        u = -1;

        /* Find minimum tentative node */

        for (j = 0; j < n; j++)
        {
            if (visited[j] == 0 && dist[j] < min)
            {
                min = dist[j];
                u = j;
            }
        }

        if (u == -1)
        {
            break;
        }

        visited[u] = 1;


        /* Update neighbors */

        for (j = 0; j < n; j++)
        {
            if (visited[j] == 0 &&
                cost[u][j] != INF)
            {
                if (dist[u] + cost[u][j] < dist[j])
                {
                    dist[j] = dist[u] + cost[u][j];

                    if (u == source)
                    {
                        nextHop[j] = j;
                    }
                    else
                    {
                        nextHop[j] = nextHop[u];
                    }
                }
            }
        }
    }


    /* Store final results */

    for (i = 0; i < n; i++)
    {
        finalDist[source][i] = dist[i];

        finalNextHop[source][i] = nextHop[i];
    }
}


/* Run Dijkstra from every node */
void calculateFinalMatrix()
{
    int i;

    for (i = 0; i < n; i++)
    {
        dijkstra(i);
    }
}


/* Display Final Routing / Distance Matrix */
void displayFinalMatrix()
{
    int i, j;

    printf("\n\n================================================");
    printf("\n        FINAL ROUTING / DISTANCE MATRIX");
    printf("\n================================================");

    printf("\n\n\t");

    for (j = 0; j < n; j++)
    {
        printf("%-8s", router[j]);
    }

    printf("\n");

    for (i = 0; i < n; i++)
    {
        printf("%-8s", router[i]);

        for (j = 0; j < n; j++)
        {
            if (finalDist[i][j] == INF)
            {
                printf("%-8s", "INF");
            }
            else
            {
                printf("%-8d", finalDist[i][j]);
            }
        }

        printf("\n");
    }
}


/* Display final routing table for one node */
void displayNodeWise()
{
    char name[20];

    int source;
    int i;

    printf("\nEnter source node: ");
    scanf("%s", name);

    source = findRouter(name);

    if (source == -1)
    {
        printf("\nInvalid router name!\n");
        return;
    }

    printf("\n\n================================================");
    printf("\n      FINAL ROUTING TABLE FOR NODE %s",
           router[source]);
    printf("\n================================================");

    printf("\n\nDestination\tCost\tNext Hop");

    for (i = 0; i < n; i++)
    {
        printf("\n%-15s", router[i]);

        if (finalDist[source][i] == INF)
        {
            printf("INF\t-");
        }
        else
        {
            printf("%d\t",
                   finalDist[source][i]);

            if (i == source)
            {
                printf("-");
            }
            else
            {
                printf("%s",
                       router[finalNextHop[source][i]]);
            }
        }
    }

    printf("\n");
}


/* Main */
int main()
{
    int i, j;

    int edges;

    int graphType;

    int u, v;

    int edgeCost;

    int choice;

    char source[20];
    char destination[20];

    char again;


    /* Number of routers */

    printf("Enter number of routers: ");
    scanf("%d", &n);


    /* Router names */

    printf("\nEnter router names separated by spaces:\n");

    for (i = 0; i < n; i++)
    {
        scanf("%s", router[i]);
    }


    /* Initialize cost matrix */

    for (i = 0; i < n; i++)
    {
        for (j = 0; j < n; j++)
        {
            if (i == j)
            {
                cost[i][j] = 0;
            }
            else
            {
                cost[i][j] = INF;
            }
        }
    }


    /* Graph type */

    printf("\n========================================");
    printf("\n              GRAPH TYPE");
    printf("\n========================================");

    printf("\n1. Weighted Graph");
    printf("\n2. Unweighted Graph");

    printf("\nEnter choice: ");
    scanf("%d", &graphType);


    if (graphType != 1 && graphType != 2)
    {
        printf("\nInvalid choice!");
        return 0;
    }


    /* Number of edges */

    printf("\nEnter number of edges: ");
    scanf("%d", &edges);


    /* Enter edges */

    printf("\nEnter edges as Source Destination:\n");

    for (i = 0; i < edges; i++)
    {
        printf("\nEdge %d: ", i + 1);

        scanf("%s %s", source, destination);

        u = findRouter(source);
        v = findRouter(destination);


        if (u == -1 || v == -1)
        {
            printf("\nInvalid router name!");

            i--;

            continue;
        }


        /* Weighted graph */

        if (graphType == 1)
        {
            printf("Enter cost: ");
            scanf("%d", &edgeCost);
        }

        /* Unweighted graph */

        else
        {
            edgeCost = 1;
        }


        /* Undirected network */

        cost[u][v] = edgeCost;
        cost[v][u] = edgeCost;
    }


    /*
       Calculate shortest paths
       using Dijkstra
    */

    calculateFinalMatrix();


    /* Menu */

    do
    {
        printf("\n\n================================================");
        printf("\n           LINK-STATE ROUTING MENU");
        printf("\n================================================");

        printf("\n1. Display LSPs");
        printf("\n2. Display Initial LSDB");
        printf("\n3. Display Final Routing Matrix");
        printf("\n4. Display Node-wise Routing Table");
        printf("\n5. Exit");

        printf("\n\nEnter your choice: ");
        scanf("%d", &choice);


        if (choice == 1)
        {
            displayLSP();
        }

        else if (choice == 2)
        {
            displayInitialMatrix();
        }

        else if (choice == 3)
        {
            displayFinalMatrix();
        }

        else if (choice == 4)
        {
            displayNodeWise();
        }

        else if (choice == 5)
        {
            printf("\nProgram terminated.\n");
            break;
        }

        else
        {
            printf("\nInvalid choice!");
        }


        if (choice != 5)
        {
            printf("\n\nDo you want to continue? (Y/N): ");
            scanf(" %c", &again);
        }
        else
        {
            again = 'N';
        }

    } while (again == 'Y' || again == 'y');


    return 0;
}
